version: "3.8"

networks:
  bridge:
    driver: bridge

services:
  localstack:
    image: 'localstack/localstack'
    container_name: 'localstack'
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=us-east-1
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - AWS_ACCESS_KEY_ID=qwer
      - AWS_SECRET_ACCESS_KEY=1234
      - AWS_DEFAULT_REGION=us-east-1
    ports:
      - '4566:4566'
    networks:
      - bridge

  sample-app:
    build:
      context: .
    depends_on:
      - localstack
    ports:
      - '8080:8080'
    environment:
      - "HTTP_PORT=8080"
      - "AWS_ACCESS_KEY_ID=dummy-key-id"
      - "AWS_SECRET_ACCESS_KEY=dummy-secret-key"
      - "AWS_ENDPOINT=http://localstack:4566"
    networks:
      - bridge
