FROM node:18-slim

WORKDIR /app

COPY package.json .
COPY package-lock.json . 

RUN npm install
COPY src/ /app/src/

ARG HTTP_PORT
ARG AWS_ENDPOINT 
ARG MYSQL_HOST
ARG MYSQL_PORT
ARG MYSQL_DATABASE
ARG MYSQL_USER
ARG MYSQL_PASSWORD

ENV HTTP_PORT=$HTTP_PORT
ENV AWS_ENDPOINT=$AWS_ENDPOINT
ENV MYSQL_HOST=$MYSQL_HOST
ENV MYSQL_PORT=$MYSQL_PORT
ENV MYSQL_DATABASE=$MYSQL_DATABASE
ENV MYSQL_USER=$MYSQL_USER
ENV MYSQL_PASSWORD=$MYSQL_PASSWORD

EXPOSE 8080
CMD ["npm", "start"]
